flake: update to NixOS 25.05
- fixed mautrix-telegram, it now registers itself with matrix-synapse https://github.com/NixOS/nixpkgs/pull/389679

Fix errors:
error: The option `systemd.services.mautrix-telegram.serviceConfig.User' has conflicting definition values:
      - In `/nix/store/2g8wdl6qgkpk9dhj9rir7zkf9nxnjqzw-source/nixos/modules/services/matrix/mautrix-telegram.nix': "mautrix-telegram"
      - In `/nix/store/zbr22r4w2z0gpjpda7l0gwajklc3f7zn-source/flake.nix, via option flake.nixosModules.matrix-telegram': "matrix-synapse"

error: The ‘gnome.gnome-shell’ was moved to top-level. Please use ‘pkgs.gnome-shell’ directly.

nextcloud31Packages.apps.recognize build failure https://github.com/NixOS/nixpkgs/pull/400158

Fix warnings:
trace: evaluation warning: treefmt2 has been renamed to treefmt

flake.lock changes

• Updated input 'disko':
    'github:nix-community/disko/da6109c917b48abc1f76dd5c9bf3901c8c80f662' (2025-07-04)
  → 'github:nix-community/disko/16b74a1e304197248a1bc663280f2548dbfcae3c' (2025-07-07)
• Updated input 'home-manager':
    'github:nix-community/home-manager/d5f1f641b289553927b3801580598d200a501863' (2025-05-19)
  → 'github:nix-community/home-manager/9b0873b46c9f9e4b7aa01eb634952c206af53068' (2025-07-06)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/1f426f65ac4e6bf808923eb6f8b8c2bfba3d18c5' (2025-06-23)
  → 'github:nixos/nixpkgs/88983d4b665fb491861005137ce2b11a9f89f203' (2025-07-08)
• Removed input 'nixpkgs-draupnir'
• Updated input 'simple-nixos-mailserver':
    'gitlab:simple-nixos-mailserver/nixos-mailserver/14857a0309d7bbdf7c51bbfa309d0d13448ae77e' (2025-05-05)
  → 'gitlab:simple-nixos-mailserver/nixos-mailserver/53007af63fade28853408370c4c600a63dd97f41' (2025-05-23)
• Added input 'simple-nixos-mailserver/git-hooks':
    'github:cachix/git-hooks.nix/16ec914f6fb6f599ce988427d9d94efddf25fe6d' (2025-06-24)
• Added input 'simple-nixos-mailserver/git-hooks/flake-compat':
    follows 'simple-nixos-mailserver/flake-compat'
• Added input 'simple-nixos-mailserver/git-hooks/gitignore':
    'github:hercules-ci/gitignore.nix/637db329424fd7e46cf4185293b9cc8c88c95394' (2024-02-28)
• Added input 'simple-nixos-mailserver/git-hooks/gitignore/nixpkgs':
    follows 'simple-nixos-mailserver/git-hooks/nixpkgs'
• Added input 'simple-nixos-mailserver/git-hooks/nixpkgs':
    follows 'simple-nixos-mailserver/nixpkgs'
• Removed input 'simple-nixos-mailserver/nixpkgs-24_11'
• Added input 'simple-nixos-mailserver/nixpkgs-25_05':
    follows 'nixpkgs'
• Updated input 'unstable':
    'github:nixos/nixpkgs/3016b4b15d13f3089db8a41ef937b13a9e33a8df' (2025-06-30)
  → 'github:nixos/nixpkgs/9807714d6944a957c2e036f84b0ff8caf9930bc0' (2025-07-08)