forgejo: use latest version from unstable for security fixes
error: Package ‘forgejo-1.20.6-1-unstable-2024-04-18’ in /nix/store/qk1dpz44db85rhd8lr4j6i2hkn9j5hg4-source/pkgs/applications/version-management/forgejo/default.nix:147 is marked as insecure, refusing to evaluate.

Known issues:
- Forgejo v1.20.x is EOL
- OAuth2 implementation does not always require authentication for public clients