fix(ci): avoid nix trying to use GH access-token
The GITHUB_TOKEN env var is set on each step by
https://code.forgejo.org/forgejo/runner, but only to communicate with
forgejo to access the repo (if it is private)

error: unable to download 'https://api.github.com/repos/srid/nixos-flake/tarball/4e422edf6b511f8e214b392cf1a0d4707a0399a4': HTTP error 401